### ISSUE TITLE
API Key Request

### ISSUE THREAD

**Issue by hsccdc** [nhscc/elections.api.hscc.bdpa.org#1]
Good afternoon,

The D.C. chapter and Baltimore chapter would like to request an API key.

**Comment by hsccdc** [comment]
Good afternoon,

I just wanted to follow up on the API key request for the Baltimore and D.C. chapter.

**Comment by Xunnamius** [comment]
Good morning,

API keys will be handed out to every chapter who has responded to the survey (via email) when the API goes public on Sunday. If you don't receive a key then, please respond here.
