### ISSUE TITLE
Step 5

### ISSUE THREAD

**Issue by jmusgrovejr** [nhscc/elections.api.hscc.bdpa.org#3]
npm run test command is listed as "run npm test"

**Comment by Xunnamius** [comment]
Is this in the README? This is what I see:

```
4. If you want to quickly test the API, run `npm test`
5. To run the API in development mode, run `npm run dev`
```
`npm test` is an alias of `npm run test`. You should be able to run the command `npm test` in your terminal if the API repo is your current working directory.
