### ISSUE TITLE
Npm Install Error

### ISSUE THREAD

**Issue by AmayaT17** [nhscc/elections.api.hscc.bdpa.org#4]
[2020-06-06T15_37_00_422Z-debug.log](https://github.com/nhscc/elections.api.hscc.bdpa.org/files/4740577/2020-06-06T15_37_00_422Z-debug.log)

Hey I'm having trouble with npm install, I'm also using Windows 10 Home

**Comment by Xunnamius** [comment]
Thanks for the helpful log file! Hmm, seems the `npm-force-resolutions` package is failing on your setup. That's interesting. The package runs during the preinstall step and forcefully updates packages that have known vulnerabilities to a more secure version. This isn't super important when running in development mode, so it should be safe to disable this security step:

1. Open `package.json`, [delete L19](https://github.com/nhscc/elections.api.hscc.bdpa.org/blob/master/package.json#L19), and save
2. Run `npm install` again. If it worked, npm will tell you about one or more vulnerabilities it found after installation completes successfully

If this doesn't work, comment here and I'll reopen.
